depromeet/critix-server

.github/workflows/BuilldCheck.yml
.github/workflows/DeployToDev.yml
Dockerfile
infra/development/docker-compose.yml

- close #9 
- PR open 시 빌드 체크 워크플로 작성
- Dockerfile 작성
- docker-compose.yml 및 자동화 배포 파이프라인 구축
1. PR이 열릴 때 GitHub Actions를 활용한 빌드 체크 워크플로를 추가하여 컴파일 오류를 사전에 검토할 수 있도록 하였습니다.  
2. `develop` 브랜치에 코드가 푸시되면 자동 배포 파이프라인이 실행됩니다. 
이 과정에서 `scp`를 이용해 `docker-compose.yml`을 개발 서버로 전송한 후, 해당 파일을 기반으로 이미지를 `pull`하고 컨테이너를 실행합니다.
3. 모든 환경 변수는 노션에 업데이트 해놓았습니다.

chore: 개발 서버 docker compose 기반 환경 구축 및 배포 파이프라인 작성

---

src/main/java/depromeet/onepiece/common/error/CustomResponse.java
src/main/java/depromeet/onepiece/common/error/GlobalControllerAdvice.java
src/main/java/depromeet/onepiece/common/error/GlobalErrorCode.java
src/main/java/depromeet/onepiece/common/error/GlobalException.java

- #13 
- 프로젝트내 글로벌 에러 설정
- 커스텀하게 에러코드를 지정하고 상태코드랑 메시지를 설정해야 합니다. 

feat : 글로벌 에러 핸들러 설정 (#13)

---

build.gradle
src/main/java/depromeet/onepiece/common/config/MongoConfig.java
src/main/java/depromeet/onepiece/common/domain/BaseTimeDocument.java
src/main/java/depromeet/onepiece/feedback/domain/AdditionalChat.java
src/main/java/depromeet/onepiece/feedback/domain/EvaluationItem.java
src/main/java/depromeet/onepiece/feedback/domain/EvaluationType.java
src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerPage.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerProject.java
src/main/java/depromeet/onepiece/feedback/domain/OverallEvaluation.java
src/main/java/depromeet/onepiece/portfolio/domain/Image.java
src/main/java/depromeet/onepiece/portfolio/domain/Portfolio.java
src/main/java/depromeet/onepiece/user/domain/OAuthProviderType.java
src/main/java/depromeet/onepiece/user/domain/User.java

- #15 
- 몽고db erd 설계
-
- 기본 설계는 다음과 같은데 필요한 필드 있으면 추가하고 공유해주시면 됩니다.

feat : entity 설계

---

infra/development/docker-compose.yml
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

- #17 
- 몽고DB 설정 
- 트랜잭션 지원을 위한 레플리카 셋 설정
- 서버 인스턴스 내 .env 파일 확인 할 것 

feat : mongodb 설정 #17

---

src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

- close #28 
- 스웨거 서버 URL 불일치로 인한 CORS 이슈 픽스
- 각 환경에 따른 스웨거 요청 서버 URL 매핑
- SERVER_URL 환경 변수 추가

fix: 스웨거 서버 URL 불일치로 인한 CORS 이슈 픽스

---

src/main/java/depromeet/onepiece/feedback/domain/FeedbackDetail.java
src/main/java/depromeet/onepiece/feedback/domain/OverallEvaluation.java
src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java

- closed #34 
Feedback 도큐먼트에서 **`강점 분석,`** **`개선할 점 및 해결방안`** 필드가 누락되어서 추가하였습니다.

fix : OverallEvaluation 필드 누락 추가

---

aiflow-scheduler.puml
src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
src/main/java/depromeet/onepiece/common/config/WebMvcConfig.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTService.java
src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
src/main/java/depromeet/onepiece/feedback/command/presentation/response/FeedbackResponse.java
src/main/java/depromeet/onepiece/feedback/command/presentation/response/OverallFeedbackResponse.java
src/main/java/depromeet/onepiece/feedback/command/presentation/response/RecentFeedbackListResponse.java
src/main/java/depromeet/onepiece/feedback/command/presentation/response/RemainCountResponse.java

- #44 
- mongodb 직렬화 역직렬화 구현
- 목 api 3개 개발

feat : 목 api 3개 개발, mongodb 직렬화 역직렬화 구현

---

.github/workflows/DeployToDev.yml
infra/development/docker/docker-compose.yml
infra/development/nginx/nginx.conf
src/main/java/depromeet/onepiece/common/auth/presentation/LoginController.java

- close #48 
-  nginx 설정 docker-compose.yml 경로 수정
- dev 환경에서 테스트 가능하도록 LoginController 적용 Profile 변경
https 적용은 추후 진행 합니다.

chore: nginx 설정 docker-compose.yml 경로 수정

---

build.gradle
src/main/java/depromeet/onepiece/common/config/WebMvcConfig.java
src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
src/main/java/depromeet/onepiece/feedback/domain/EvaluationDetail.java
src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackContent.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackDetail.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerPage.java
src/main/java/depromeet/onepiece/feedback/domain/OverallEvaluation.java
src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackNotFoundException.java
src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackQueryExceptionCode.java
src/main/java/depromeet/onepiece/feedback/query/domain/FeedbackQueryRepository.java
src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackMongoRepository.java
src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java

- #54 
- 응답 Feedback으로 변경
- 일부 스키마 변경

feat : 피드백 디테일 로직 구현

---

src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java

fix : mock 응답 수정

---

.github/workflows/DeployToDev.yml
src/main/java/depromeet/onepiece/common/config/SecurityConfig.java

- close #71 
strip_components 위 값 때문에 배포 시 서버 내부에 추가 디렉토리가 생성되는 문제가 있었고 이를 수정하였습니다.

fix: 개발 서버 CORS 이슈 픽스 및 docker-compose.yml strip_components 값 변경

---

src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackContent.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackContentDetail.java

- #67 
- 피드백 응답 구조 수정
```json
{
"createdAt": null,
"updatedAt": null,
"deletedAt": null,
"id": "67ceebcb241e44219d61337b",
"userId": "67ceebcb241e44219d61337c",
"portfolioId": "67ceebcb241e44219d61337d",
"overallEvaluation": {
"summary": "종합 평가 요약 ",
"jobFit": {
"score": 80,
"review": "직무 적합성이 높습니다."
},
"logicalThinking": {
"score": 75,
"review": "논리적인 사고력이 돋보입니다."
},
"writingClarity": {
"score": 85,
"review": "글쓰기 표현이 명확합니다."
},
"layoutReadability": {
"score": 90,
"review": "레이아웃이 가독성이 높습니다."
},
"strengths": [
{
"title": "데이터 기반의 디자인 사고",
"content": [
"a/b 테스트 설문조사",
"단순한 미적감각이 아니라 뛰어남"
]
},
{
"title": "데이터 기반의 디자인 사고",
"content": [
"a/b 테스트 설문조사",
"단순한 미적감각이 아니라 뛰어남",
"a/b 테스트 설문조사",
"단순한 미적감각이 아니라 뛰어남"
]
}
],
"improvements": [
{
"title": "UI/UX 디자인 과정을 시각적으로 추가하기",
"content": [
"더 강조할 …
```

refactor : 피드백 entity, 응답 수정

---

src/main/java/depromeet/onepiece/common/config/SecurityConfig.java

- #77
- spotless 코드 포맷팅 CI 에러 해결
개발 서버 정상 배포 확인했습니다

fix: 코드 포맷팅 CI 에러 해결

---

src/main/java/depromeet/onepiece/OnepieceApplication.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandService.java
src/main/java/depromeet/onepiece/feedback/command/domain/FeedbackCommandRepository.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackCommandRepositoryImpl.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackService.java
src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
src/main/java/depromeet/onepiece/feedback/command/presentation/response/StartFeedbackResponse.java
src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackStatus.java

-  close #81 
1. requet : fileId 
2. 비동기로 chatGPT 요청 시작
3. Feedback status 추가 후 feedbackId 반환

feat : Feedback 요청 시작 api 구현

---

.github/workflows/DeployToDev.yml

- #88 
- 헬스 체크 스크립트
- 슬랙 연동 알림 봇 연동

refactor: 개발 서버 배포 시 헬스 체크 스크립트 추가

---

src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
src/main/java/depromeet/onepiece/file/query/application/FileQueryService.java
src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryMongoRepository.java
src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryRepository.java
src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryRepositoryImpl.java

- close #94 
- 파일 이름 암호화되어서 나가는거 수정
- 쿼리 최적화

fix : 피드백 전체 목록에서 파일 이름 복호화하게 변경

---

src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java

fix : 포트폴리오 피드백 호출 API userId String으로 되어잇던거 수정

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandService.java
src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java

fix : 포트폴리오 응답 파일 제목 추가

---

src/main/java/depromeet/onepiece/feedback/domain/EditPair.java
src/main/java/depromeet/onepiece/feedback/domain/PageFeedbackContent.java
src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java

fix : 포트폴리오 페이지 피드백 응답 수정

---

src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java

fix : 포트폴리오 응답 수정

---

infra/ncp/TextExtractAction.py

- #111 
- NCP 콘솔에서 작업할 때 잘못 수정해도 롤백할 수가 없어서 코드 히스토리 추적, 저장을 위해 액션 코드 추가했습니다.

feat : NCP Action 코드 추가

---

src/main/java/depromeet/onepiece/feedback/command/application/ChatGPTConstants.java

- #120 
1. 페이지 별 피드백을 따로 요청할 경우 -> `PAGE_FEEDBACK` 프롬프트, 스키마 사용
2. 기존대로 프로젝트 피드백을 한 번에 요청할 경우 -> `COMBINED_FEEDBACK` 프롬프트, 스키마 사용
3. 기존에 사용하던 프롬프트, 스키마 -> `PROJECT(사용 x)`
```
{
"projects": [
{
"projectName": "토스 새소식 프로젝트",
"projectEvaluation": {
"process": ["GOOD", "GOOD", "GOOD", "GOOD", "SOSO"],
"processReview": "문제 정의부터 실험과 결과까지 논리적으로 잘 구성되어 있습니다. 회고 부분은 조금 더 구체적인 인사이트가 담겼으면 좋았을 것 같습니다.",
"positiveFeedback": [
{
"title": "정량 데이터 활용",
"content": [
"리텐션, CTW 등 정량 데이터를 기반으로 문제를 분석한 점이 좋았습니다.",
"사용자 행동을 수치로 분석하여 신뢰도를 높였습니다."
]
},
{
"title": "그로스 전략 구성",
"content": [
"시즌성을 활용한 전략이 효과적이었습니다.",
"이벤트와 혜택 구성이 사용자 몰입도를 높였습니다."
]
},
{
"title": "포트폴리오 구성력",
"content": [
"카드 UI와 강조 포인트가 가독성을 높였습니다.",
"섹션 분할이 명확해 흐름을 쉽게 따라갈 수 있었습니다."
]
}
],
"negativeFeedback": [
{
"title": "회고 부족",
"content": [ …
```

feat : 프로젝트 피드백 프롬프트, 스키마 정리

---

infra/development/docker/docker-compose.yml
infra/development/docker/kafka-docker-compose.yml

- #125 
개발 서버에서 애플리케이션 서버 - 카프카 간 연동이 되지 않는 이슈를 도커 네트워크를 설정하여 픽스하였습니다. 
관련 환경 변수는 노션에 기록하였습니다.

fix: 개발 서버 kafka connection 이슈 픽스

---

src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackCommandExceptionCode.java
src/main/java/depromeet/onepiece/feedback/command/application/exception/GetOCRResultFailedException.java
src/main/java/depromeet/onepiece/feedback/command/application/exception/OCRResultNotFoundException.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/S3OCRJsonPoller.java

- #123
S3에서 OCR 결과 폴링해 반환
<test>
- 오후에 테스트 후 요청 예정

feat : OCR 결과 폴링

---

src/main/java/depromeet/onepiece/common/eventsourcing/config/KafkaConfig.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java

- #
- kafka 로깅하게 변경 
- userId 삭제 
- 잘못된 분기처리 수정 

feat : userId 삭제 , kafkaConfig 오류 로깅 하게 변경

---

src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java
src/main/java/depromeet/onepiece/file/command/presentation/FileUploadController.java

- 안 쓰는 테스트 API 삭제
- 피드백 리스트 조회 API url `/feedback/list`로 수정

refactor : Controller명 변경

---

infra/production/docker/docker-compose.yml
infra/production/nginx/nginx.conf
src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java

- #146 
- nginx 관련 docker 설정을 변경

refactor: docker-compose.yml 수정

---

src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java

- #149 
- 전체 피드백 조회 시 null 값이 있는 피드백도 조회해 에러가 발생하는 문제 해결

fix : 전체 피드백 반환 로직 수정

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/S3OCRJsonPoller.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
src/main/java/depromeet/onepiece/file/command/application/PresignedUrlGenerator.java

- #152 
- `updateImageUrls()` 메서드에서 presigned URL 생성 시 잘못된 경로(`.../processed/processed`)가 생성되어 반환이 안 되는 이슈 해결 
- 전체 피드백, 프로젝트 별 피드백 모두 ocr 결과 반환

fix : presigned URL 생성 경로 오류 수정,  ocr 결과 호출 

---

src/main/java/depromeet/onepiece/common/config/SecurityConfig.java

fix: production CORS 이슈 픽스

---

.github/workflows/DeployToProd.yml

- #157 
- `critix.kr` 도메인 CORS 이슈 픽스
- 도커 이미지 삭제 워크플로 개선

fix: CORS 이슈 및 도커 이미지 삭제 워크플로 개선

---

.github/workflows/DeployToProd.yml
src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandService.java
src/main/java/depromeet/onepiece/feedback/command/infrastructure/S3OCRJsonPoller.java
src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerPage.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
src/main/java/depromeet/onepiece/file/command/application/ObjectStorageFileUploader.java
src/main/java/depromeet/onepiece/file/command/application/PresignedUrlGenerator.java
src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentRepository.java
src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentRepositoryImpl.java
src/main/resources/application-prod.yml

- close #159 
- 로그인 이슈 및 CORS 이슈를 해결함
- production 배포 진행

release: production 배포

---

src/main/java/depromeet/onepiece/common/eventsourcing/consumer/GPTEventConsumer.java
src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java

feat : userName 전달, 로깅 추가

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java

- #164 
- userName 삭제
- 프로젝트 대표 이미지 presignedUrl 생성 후 업데이트

fix : 프로젝트 대표 이미지 전달

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java

fix : userName 추가

---

src/main/resources/application.yml

refactor: 토큰 만료 기간 연장

---

src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java

fix : 이미지 경로 수정

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
src/main/resources/application.yml

Develop > Main 

---

src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java

hotfix : 페이지 별 피드백 중에서 비어있는거 필터링

---

src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryMongoRepository.java
src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepository.java
src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java

fix : 피드백 반환 최신순 정렬

---

src/main/resources/logback-spring.xml

- #189 
- 운영 서버 환경에서 로그백을 사용한 로깅을 하도록 합니다

fix: 프로덕션 콘솔 로깅 허용

---

src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java

release : 유저 이름 조회 수정 (#193)
